import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: spacing.m,
    height: 64,
    backgroundColor: 'rgba(241, 245, 249, 0.8)', // slate-50/80
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s,
  },
  headerTitle: {
    fontFamily: typography.fontFamilies.headlineBold,
    fontSize: typography.sizes.h4,
    color: colors.primaryContainer,
  },
  content: {
    paddingHorizontal: spacing.l,
    paddingTop: spacing.xl,
    paddingBottom: spacing.xxxl,
  },
  statusSection: {
    alignItems: 'center',
    marginBottom: spacing.xxl,
  },
  radarContainer: {
    width: 80,
    height: 80,
    borderRadius: spacing.borderRadiusPill,
    backgroundColor: colors.surfaceVariant,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.l,
  },
  radarInner: {
    width: 64,
    height: 64,
    borderRadius: spacing.borderRadiusPill,
    backgroundColor: colors.primaryContainer,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusTitle: {
    fontFamily: typography.fontFamilies.headlineBold,
    fontSize: typography.sizes.h2,
    color: colors.textPrimary,
    marginBottom: spacing.s,
  },
  statusDesc: {
    fontFamily: typography.fontFamilies.bodyMedium,
    fontSize: typography.sizes.subtext,
    color: colors.textSecondary,
    marginBottom: spacing.l,
  },
  scanButton: {
    backgroundColor: colors.primaryContainer,
    paddingVertical: spacing.m,
    paddingHorizontal: spacing.xl,
    borderRadius: spacing.borderRadiusPill,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.s,
    elevation: 4,
    shadowColor: colors.primaryContainer,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
  },
  scanButtonText: {
    color: colors.textInverse,
    fontFamily: typography.fontFamilies.bodyBold,
    fontSize: typography.sizes.body,
  },
  devicesList: {
    gap: spacing.m,
  },
  deviceCard: {
    backgroundColor: colors.surface,
    padding: spacing.l,
    borderRadius: spacing.borderRadiusLarge,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.border,
  },
  deviceCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.m,
  },
  deviceIconContainer: {
    width: 56,
    height: 56,
    borderRadius: spacing.borderRadius,
    backgroundColor: colors.surfaceVariant,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deviceImage: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  deviceName: {
    fontFamily: typography.fontFamilies.headlineBold,
    fontSize: typography.sizes.body,
    color: colors.textPrimary,
    marginBottom: 4,
  },
  deviceStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  deviceStatusTextStrong: {
    fontFamily: typography.fontFamilies.bodyMedium,
    fontSize: typography.sizes.caption,
    color: colors.primary,
    textTransform: 'uppercase',
  },
  deviceStatusTextWeak: {
    fontFamily: typography.fontFamilies.bodyMedium,
    fontSize: typography.sizes.caption,
    color: colors.textSecondary,
    textTransform: 'uppercase',
  },
  connectButtonPrimary: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.l,
    paddingVertical: spacing.s,
    borderRadius: spacing.borderRadiusPill,
    elevation: 2,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  connectButtonSecondary: {
    backgroundColor: colors.surfaceVariant,
    paddingHorizontal: spacing.l,
    paddingVertical: spacing.s,
    borderRadius: spacing.borderRadiusPill,
  },
  connectButtonTextPrimary: {
    color: colors.textInverse,
    fontFamily: typography.fontFamilies.bodyBold,
    fontSize: typography.sizes.caption,
  },
  connectButtonTextSecondary: {
    color: colors.primary,
    fontFamily: typography.fontFamilies.bodyBold,
    fontSize: typography.sizes.caption,
  },
  helpCard: {
    marginTop: spacing.xxl,
    padding: spacing.l,
    borderRadius: spacing.borderRadiusLarge,
    backgroundColor: colors.surfaceVariant,
    borderWidth: 1,
    borderColor: colors.border,
  },
  helpIconContainer: {
    padding: spacing.s,
    backgroundColor: colors.surface,
    borderRadius: spacing.borderRadius,
    alignSelf: 'flex-start',
    marginBottom: spacing.m,
  },
  helpTitle: {
    fontFamily: typography.fontFamilies.headlineBold,
    fontSize: typography.sizes.body,
    color: colors.textPrimary,
    marginBottom: spacing.xs,
  },
  helpDesc: {
    fontFamily: typography.fontFamilies.body,
    fontSize: typography.sizes.subtext,
    color: colors.textSecondary,
    lineHeight: typography.lineHeights.subtext,
    marginBottom: spacing.m,
  },
  helpLink: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  helpLinkText: {
    color: colors.primary,
    fontFamily: typography.fontFamilies.bodyBold,
    fontSize: typography.sizes.caption,
  },
  iconPrimary: {
    color: colors.primary,
  },
  iconSecondary: {
    color: colors.textSecondary,
  },
  noDevices: {
    textAlign: 'center',
    marginTop: 20,
    fontFamily: typography.fontFamilies.body,
    fontSize: typography.sizes.body,
    color: colors.textSecondary,
  },
  liveWeightText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
});
